EX_NAME=seidel1_l2tile
EX_FILE=seidel1_l2tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_seidel1_l2tile_eqclass.csv"
PRF_FL="linv_seidel1_l2tile.txt"
BCNAME="seidel1_l2tile"
LEVEL=../..

include ../../common.mk
