EX_NAME=lu1_l2tile
EX_FILE=lu1_l2tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_lu1_l2tile_eqclass.csv"
PRF_FL="linv_lu1_l2tile.txt"
BCNAME="lu1_l2tile"
LEVEL=../..

include ../../common.mk
