EX_NAME=seidel-2d
EX_FILE=seidel-2d.c
FN_LIST="kernel_seidel_2d"
PRF_DATA_FILE="gep_seidel-2d_eqclass.csv"
BB_LIST="ignore"
BCNAME="seidel-2d"
PRF_FL="linv_seidel-2d.txt"
LEVEL=../..

include ../../common.mk
