EX_NAME=cholesky
EX_FILE=cholesky.c
FN_LIST="kernel_cholesky"
BB_LIST="ignore"
PRF_DATA_FILE="gep_cholesky_eqclass.csv"
BCNAME="cholesky"
PRF_FL="linv_cholesky.txt"
LEVEL=../../../

include ../../../common.mk
