EX_NAME=fdtd-2d1_orig
EX_FILE=fdtd-2d1_orig.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_fdtd-2d1_orig_eqclass.csv"
PRF_FL="linv_fdtd-2d1_orig.txt"
BCNAME="fdtd-2d1_orig"
LEVEL=../..

include ../../common.mk
