EX_NAME=gesummv
EX_FILE=gesummv.c
FN_LIST="kernel_gesummv"
BB_LIST="ignore"
PRF_DATA_FILE="gep_gesummv_eqclass.csv"
BCNAME="gesummv"
PRF_FL="linv_gesummv.txt"
LEVEL=../../../

include ../../../common.mk
