EX_NAME=jac1_l2tile
EX_FILE=jac1_l2tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_jac1_l2tile_eqclass.csv"
PRF_FL="linv_jac1_l2tile.txt"
BCNAME="jac1_l2tile"
LEVEL=../..

include ../../common.mk
