EX_NAME=seidel1_ncbt
EX_FILE=seidel1_ncbt.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_seidel1_ncbt_eqclass.csv"
PRF_FL="linv_seidel1_ncbt.txt"
BCNAME="seidel1_ncbt"
LEVEL=../..

include ../../common.mk
