EX_NAME=seidel1_tile
EX_FILE=seidel1_tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_seidel1_tile_eqclass.csv"
PRF_FL="linv_seidel1_tile.txt"
BCNAME="seidel1_tile"
LEVEL=../..

include ../../common.mk
