EX_NAME=jac1_unroll
EX_FILE=jac1_unroll.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_jac1_unroll_eqclass.csv"
PRF_FL="linv_jac1_unroll.txt"
BCNAME="jac1_unroll"
LEVEL=../..

include ../../common.mk
