EX_NAME=seidel1_orig
EX_FILE=seidel1_orig.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_seidel1_orig_eqclass.csv"
PRF_FL="linv_seidel1_orig.txt"
BCNAME="seidel1_orig"
LEVEL=../..

include ../../common.mk
