EX_NAME=jacobi-2d
EX_FILE=jacobi-2d.c
FN_LIST="kernel_jacobi_2d"
PRF_DATA_FILE="gep_jacobi-2d_eqclass.csv"
BB_LIST="ignore"
BCNAME="jacobi-2d"
PRF_FL="linv_jacobi-2d.txt"
LEVEL=../..

include ../../common.mk
